[project]
name = "cremalink-ha"
version = "v0.1.0b9"
description = "Cremalink for Home-Assistant Add-on & Integration"
requires-python = ">=3.13.2"
dependencies = [
    "homeassistant>=2026.1.0",
    "cremalink==0.1.0b20"
]
